moduledir '/etc/puppet/modules'

mod 'puppetlabs/stdlib'
mod 'nanliu/staging'
mod 'camptocamp/archive'
mod 'maestrodev/ssh_keygen'

# NOTE: The Puppetlabs java module doesn't work with amazon linux (wtf), so we have to add a fork below
#mod 'puppetlabs/java'
mod 'java',
  :git => 'https://github.com/sladd0175/puppetlabs-java'

# My modules
mod 'superbuilds',
  :git => 'https://github.com/bryantrobbins/puppet-superbuilds'

# The Jenkins module sucks at security so I am working from my own fork for now
mod 'jenkins',
  :git => 'https://github.com/bryantrobbins/puppet-jenkins'

